package generator

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"goforge/internal/astedit"
)

// wireFeature makes an entity's handler actually reachable over HTTP.
// Generating layer FILES is not enough: nothing would reference them,
// and Go discards unimported packages at build time. Two edits to
// existing files close the gap:
//
//  1. the entity's model type is appended to internal/model/model.go
//     (all three layers reference it);
//  2. for handlers, the wiring statements are appended to
//     registerRoutes in cmd/server/main.go, with the layer packages
//     added to its imports.
//
// Both edits are idempotent, so running `goforge generate handler
// user` twice changes nothing the second time.
func wireFeature(dir string, data Data, kind Kind, templates fs.FS) error {
	if err := ensureModelType(dir, data); err != nil {
		return err
	}
	if kind != KindHandler {
		// Only the handler is an entry point; service and repository
		// files compile standalone.
		return nil
	}

	// main.go references all three layer packages, so generate any
	// that are missing (overwriting nothing).
	for _, k := range []Kind{KindService, KindRepository} {
		path := layerPath(dir, k, data.Name)
		if _, err := os.Stat(path); !errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if _, err := renderLayer(dir, Request{Kind: k, Name: data.Name}, data, templates); err != nil {
			return fmt.Errorf("generate missing %s layer for wiring: %w", k, err)
		}
	}

	mainPath := filepath.Join(dir, "cmd", "server", "main.go")
	// Every variable carries the entity prefix: registerRoutes accumulates
	// wiring for several entities, so generic names like "repo" would
	// redeclare (and mix types) across generate runs.
	repoVar := Camel(data.Name) + "Repo"
	svcVar := Camel(data.Name) + "Svc"
	handlerVar := Camel(data.Name) + "Handler"
	stmts := fmt.Sprintf(
		"%s := repository.New%sRepository()\n%s := service.New%sService(%s)\n%s := handler.New%sHandler(%s)\n%s.Register(mux)",
		repoVar, data.Pascal,
		svcVar, data.Pascal, repoVar,
		handlerVar, data.Pascal, svcVar,
		handlerVar,
	)
	imports := []string{
		data.Module + "/internal/handler",
		data.Module + "/internal/repository",
		data.Module + "/internal/service",
	}
	if _, err := astedit.EnsureFuncWiring(mainPath, "registerRoutes", imports, stmts, "New"+data.Pascal+"Handler("); err != nil {
		return fmt.Errorf("wire %s: %w", mainPath, err)
	}
	return nil
}

// layerPath returns the output file path for one kind.
func layerPath(dir string, kind Kind, name string) string {
	spec := kindSpecs[kind]
	return filepath.Join(dir, "internal", spec.dir, name+".go")
}

// ensureModelType appends `type <Pascal> struct{ID, Name string}` to
// internal/model/model.go when the type is not declared yet. Every
// generated layer references the type, including standalone service
// and repository generation.
func ensureModelType(dir string, data Data) error {
	modelPath := filepath.Join(dir, "internal", "model", "model.go")
	decl := fmt.Sprintf(
		"// %s is a domain type generated by goforge.\ntype %s struct {\n\tID   string\n\tName string\n}",
		data.Pascal, data.Pascal,
	)
	if _, err := astedit.EnsureType(modelPath, data.Pascal, decl); err != nil {
		return fmt.Errorf("update %s: %w", modelPath, err)
	}
	return nil
}
